#Using .env file
version: '3'

networks:
  my-network:
    driver: bridge
  my-caddy:
    external: true

services:
  app:
    image: smokezxd1147/app:prod-1.1.0
    restart: always
    container_name: cms
    ports:
      - ${SERVER_PORT}:11111
    environment: #environment of strapi 
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_SSL=false
    depends_on:
      - db
      - proxy
    networks:
      - my-network

  db:
    image: postgres:latest
    restart: always
    container_name: storage
    ports:
      - ${DB_PORTS}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - my-network

  proxy:
    image: caddy:latest
    container_name: reverse
    ports:
      - ${PROXY_PORT_http}:80
      - ${PROXY_PORT_https}:443
    environment:
      - EMAIL=user@example.com #change to your email
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - ./caddy_data:/data
      # - ./caddy_config:/config
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
   
  website:
    image: smokezxd1147/website:dev-2.2.0 
    container_name: www
    ports:
      - ${wwwport}:3000
    environment:
      - port=${wwwport}